Document: tb-pulse
Title: Debian tb-pulse Manual
Author: <insert document author here>
Abstract: This manual describes what tb-pulse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tb-pulse/tb-pulse.sgml.gz

Format: postscript
Files: /usr/share/doc/tb-pulse/tb-pulse.ps.gz

Format: text
Files: /usr/share/doc/tb-pulse/tb-pulse.text.gz

Format: HTML
Index: /usr/share/doc/tb-pulse/html/index.html
Files: /usr/share/doc/tb-pulse/html/*.html
