#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/tb-pulse" ] || [ -e "/etc/init/tb-pulse.conf" ]; then
	invoke-rc.d tb-pulse stop || exit $?
fi
# End automatically added section
